// <auto-generated />
using System;
using API_DSCS2_WEBBANGIAY.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API_DSCS2_WEBBANGIAY.Migrations
{
    [DbContext(typeof(ShoesEcommereContext))]
    [Migration("20230322033441_updateIDUpdateOnn")]
    partial class updateIDUpdateOnn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.BoSuuTap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Img")
                        .HasColumnType("text");

                    b.Property<string>("MaSanPham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("char(30)")
                        .HasColumnName("slug")
                        .IsFixedLength(true);

                    b.Property<string>("TenBoSuuTap")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id");

                    b.ToTable("BoSuuTap");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.Branchs", b =>
                {
                    b.Property<string>("MaChiNhanh")
                        .HasColumnType("char(20)");

                    b.Property<int?>("DiaChiNavigationID")
                        .HasColumnType("int");

                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IDAddress")
                        .HasColumnType("int");

                    b.Property<string>("TenChiNhanh")
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("isDefault")
                        .HasColumnType("bit");

                    b.HasKey("MaChiNhanh");

                    b.HasIndex("DiaChiNavigationID");

                    b.ToTable("Branchs");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.Brand", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MaSanPham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("createdAT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("updatedAT")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.ChiNhanh_SanPham", b =>
                {
                    b.Property<string>("MaChiNhanh")
                        .HasColumnType("char(20)");

                    b.Property<string>("MaSanPham")
                        .HasColumnType("char(10)");

                    b.Property<decimal?>("GiaVon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("SoLuongCoTheban")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongHangDangGiao")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongHangDangVe")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<int?>("TonKho")
                        .HasColumnType("int");

                    b.HasKey("MaChiNhanh", "MaSanPham");

                    b.HasIndex("MaSanPham");

                    b.ToTable("KhoHangs");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.ChiTietCoupon", b =>
                {
                    b.Property<string>("MaSanPham")
                        .HasColumnType("char(10)");

                    b.Property<string>("MaCoupon")
                        .HasColumnType("char(15)");

                    b.HasKey("MaSanPham", "MaCoupon");

                    b.HasIndex("MaCoupon");

                    b.ToTable("ChiTietCoupons");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.ChiTietHinhAnh", b =>
                {
                    b.Property<string>("MaSanPham")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .IsFixedLength(true);

                    b.Property<int>("IdHinhAnh")
                        .HasColumnType("int")
                        .HasColumnName("_id_HinhAnh");

                    b.Property<string>("IdMaMau")
                        .HasMaxLength(20)
                        .HasColumnType("char(20)");

                    b.Property<int>("IDSanPham")
                        .HasColumnType("int");

                    b.HasKey("MaSanPham", "IdHinhAnh", "IdMaMau")
                        .HasName("pk_CTHA");

                    b.HasIndex("IdMaMau");

                    b.HasIndex(new[] { "IdHinhAnh" }, "IX_ChiTietHinhAnh__id_HinhAnh");

                    b.HasIndex(new[] { "IdHinhAnh" }, "IX_HinhAnh_SanPham__id_HinhAnh");

                    b.ToTable("ChiTietHinhAnh");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.ChiTietNhapXuat", b =>
                {
                    b.Property<string>("MaSanPham")
                        .HasColumnType("char(10)");

                    b.Property<int>("IDPN")
                        .HasColumnType("int");

                    b.Property<string>("DVT")
                        .HasColumnType("char(10)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenPhieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("createdAT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("updatedAT")
                        .HasColumnType("datetime2");

                    b.HasKey("MaSanPham", "IDPN");

                    b.HasIndex("IDPN");

                    b.ToTable("ChiTietNhapXuats");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.Coupon", b =>
                {
                    b.Property<string>("MaCoupon")
                        .HasColumnType("char(15)");

                    b.Property<decimal>("GiaTri")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLanDung")
                        .HasColumnType("int");

                    b.Property<string>("TenCoupon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaCoupon");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.DanhMuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("GioiTinhCode")
                        .HasColumnType("int");

                    b.Property<int?>("ParentCategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("char(30)")
                        .HasColumnName("slug")
                        .IsFixedLength(true);

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "GioiTinhCode" }, "IX_DanhMuc_GioiTinh_Code");

                    b.ToTable("DanhMuc");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.DanhMucDetails", b =>
                {
                    b.Property<int>("danhMucId")
                        .HasColumnType("int");

                    b.Property<string>("MaSanPham")
                        .HasColumnType("char(10)");

                    b.Property<int>("IDSanPham")
                        .HasColumnType("int");

                    b.HasKey("danhMucId", "MaSanPham");

                    b.HasIndex("MaSanPham");

                    b.ToTable("DanhMucDetails");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.DiaChi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressDsc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DistrictID")
                        .HasColumnType("int");

                    b.Property<string>("DistrictName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("char(254)");

                    b.Property<int?>("IDKH")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Phone")
                        .HasColumnType("char(10)");

                    b.Property<int?>("ProvinceID")
                        .HasColumnType("int");

                    b.Property<string>("ProvinceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTaiKhoan")
                        .HasColumnType("char(20)");

                    b.Property<int?>("WardID")
                        .HasColumnType("int");

                    b.Property<string>("WardName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("IDKH");

                    b.HasIndex("TenTaiKhoan");

                    b.ToTable("DiaChis");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.GenKey", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("ID");

                    b.ToTable("Keys");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.HinhAnh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FileName")
                        .HasColumnType("char(255)")
                        .HasColumnName("file_name");

                    b.HasKey("Id");

                    b.ToTable("HinhAnh");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.KhachHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .IsFixedLength(true)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("char(30)")
                        .IsFixedLength(true);

                    b.Property<int?>("GiamGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<bool?>("Gioitinh")
                        .HasColumnType("bit")
                        .HasColumnName("gioitinh");

                    b.Property<DateTime?>("Ngaysinh")
                        .HasColumnType("date")
                        .HasColumnName("ngaysinh");

                    b.Property<string>("TenKhachHang")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal?>("TienThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("money")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("Id")
                        .HasName("pk_KH");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.LoaiPhieu", b =>
                {
                    b.Property<string>("MaPhieu")
                        .HasColumnType("char(10)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenPhieu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhieu");

                    b.ToTable("LoaiPhieu");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.MauSac", b =>
                {
                    b.Property<string>("MaMau")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .HasDefaultValueSql("('')")
                        .IsFixedLength(true);

                    b.Property<string>("TenMau")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("(N'')");

                    b.HasKey("MaMau")
                        .HasName("pk_mausac");

                    b.ToTable("MauSac");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.Message", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentMessageID")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAT")
                        .HasColumnType("datetime2");

                    b.Property<string>("creatorID")
                        .HasColumnType("char(20)");

                    b.HasKey("ID");

                    b.HasIndex("ParentMessageID");

                    b.HasIndex("creatorID");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.NCC", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("char(50)");

                    b.Property<int?>("IDDiaChi")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasColumnType("char(10)");

                    b.HasKey("ID");

                    b.HasIndex("IDDiaChi");

                    b.ToTable("NhaCungCap");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.PhieuNhapXuat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ChietKhau")
                        .HasColumnType("int");

                    b.Property<string>("CouponCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CouponNavigationMaCoupon")
                        .HasColumnType("char(15)");

                    b.Property<bool?>("DaNhapHang")
                        .HasColumnType("bit");

                    b.Property<bool?>("DaThanhToan")
                        .HasColumnType("bit");

                    b.Property<int?>("DeliveryStatus")
                        .HasColumnType("int");

                    b.Property<int?>("IDNCC")
                        .HasColumnType("int");

                    b.Property<int?>("IdDiaChi")
                        .HasColumnType("int");

                    b.Property<int?>("KhachHangNavigationId")
                        .HasColumnType("int");

                    b.Property<string>("LoaiPhieu")
                        .HasColumnType("char(10)");

                    b.Property<string>("MaChiNhanh")
                        .HasColumnType("char(20)");

                    b.Property<decimal?>("Phiship")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PhuongThucThanhToan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TienDaGiam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TienDaThanhToan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TongSoLuong")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("idKH")
                        .HasColumnType("int");

                    b.Property<string>("idTaiKhoan")
                        .HasColumnType("char(20)");

                    b.Property<int?>("status")
                        .HasColumnType("int");

                    b.Property<int?>("steps")
                        .HasColumnType("int");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CouponNavigationMaCoupon");

                    b.HasIndex("IDNCC");

                    b.HasIndex("IdDiaChi");

                    b.HasIndex("KhachHangNavigationId");

                    b.HasIndex("LoaiPhieu");

                    b.HasIndex("MaChiNhanh");

                    b.HasIndex("idTaiKhoan");

                    b.ToTable("PhieuNhapXuats");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.ReviewStar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("Avr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasColumnName("avr")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("BaSao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ba_sao")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("BonSao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("bon_sao")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("HaiSao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("hai_sao")
                        .HasDefaultValueSql("((0))");

                    b.Property<int>("IDSanPham")
                        .HasColumnType("int");

                    b.Property<string>("MaSanPham")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .IsFixedLength(true);

                    b.Property<int?>("MotSao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mot_sao")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("NamSao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("nam_sao")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "MaSanPham" }, "IX_reviewStar_MasanPham");

                    b.ToTable("reviewStar");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.RoomMessage", b =>
                {
                    b.Property<int>("MessageID")
                        .HasColumnType("int");

                    b.Property<string>("MaSanPham")
                        .HasColumnType("char(10)");

                    b.Property<string>("UserID")
                        .HasColumnType("char(20)");

                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IDSanPham")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAT")
                        .HasColumnType("datetime2");

                    b.HasKey("MessageID", "MaSanPham", "UserID");

                    b.HasIndex("MaSanPham");

                    b.HasIndex("UserID");

                    b.ToTable("RoomMessages");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Dsc")
                        .HasColumnType("ntext");

                    b.Property<int>("Giamgia")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayBatDat")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Sale");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.SanPham", b =>
                {
                    b.Property<string>("MaSanPham")
                        .HasColumnType("char(10)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<decimal?>("GiaBanLe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GiaBanSi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GiaNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GiaVon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("GiamGia")
                        .HasColumnType("int");

                    b.Property<int?>("IDAnh")
                        .HasColumnType("int");

                    b.Property<int?>("IDBrand")
                        .HasColumnType("int");

                    b.Property<string>("IDColor")
                        .HasColumnType("char(20)");

                    b.Property<string>("IDSize")
                        .HasColumnType("char(10)");

                    b.Property<int?>("IDType")
                        .HasColumnType("int");

                    b.Property<int?>("IDVat")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IdBst")
                        .HasColumnType("int")
                        .HasColumnName("_id_BST");

                    b.Property<string>("Mota")
                        .HasColumnType("ntext");

                    b.Property<string>("ParentID")
                        .HasColumnType("char(10)");

                    b.Property<string>("Slug")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("char(500)")
                        .HasColumnName("slug")
                        .IsFixedLength(true);

                    b.Property<int?>("SoLuongCoTheban")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("MaSanPham")
                        .HasName("pk_sanpham");

                    b.HasIndex("IDAnh");

                    b.HasIndex("IDBrand");

                    b.HasIndex("IDColor");

                    b.HasIndex("IDSize");

                    b.HasIndex("IDType");

                    b.HasIndex("IDVat");

                    b.HasIndex("ParentID");

                    b.HasIndex(new[] { "IdBst" }, "IX_SanPham__id_BST");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.Size", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(10)");

                    b.Property<string>("Size1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("size");

                    b.HasKey("Id");

                    b.ToTable("Sizes");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.TaiKhoan", b =>
                {
                    b.Property<string>("TenTaiKhoan")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .IsFixedLength(true);

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("char(30)")
                        .IsFixedLength(true);

                    b.Property<bool?>("Gioitinh")
                        .HasColumnType("bit");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .IsFixedLength(true);

                    b.Property<int?>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TenHienThi")
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("TienThanhToan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("addressDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("-1");

                    b.Property<int?>("idKH")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .IsFixedLength(true);

                    b.HasKey("TenTaiKhoan")
                        .HasName("pk_TK");

                    b.HasIndex("idKH");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.Type", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MaSanPham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("createdAT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("updatedAT")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.VAT", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MaSanPham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("giaTriThueDauRa")
                        .HasColumnType("int");

                    b.Property<int>("giaTriThueDauVao")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Vats");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.Branchs", b =>
                {
                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.DiaChi", "DiaChiNavigation")
                        .WithMany("Branchs")
                        .HasForeignKey("DiaChiNavigationID");

                    b.Navigation("DiaChiNavigation");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.ChiNhanh_SanPham", b =>
                {
                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.Branchs", "BranchNavigation")
                        .WithMany("KhoHangs")
                        .HasForeignKey("MaChiNhanh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.SanPham", "SanPhamNavigation")
                        .WithMany("KhoHangs")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BranchNavigation");

                    b.Navigation("SanPhamNavigation");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.ChiTietCoupon", b =>
                {
                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.Coupon", "CouponNavigation")
                        .WithMany("ChiTietCoupons")
                        .HasForeignKey("MaCoupon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.SanPham", "SanPhamNavigation")
                        .WithMany("ChiTietCoupons")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CouponNavigation");

                    b.Navigation("SanPhamNavigation");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.ChiTietHinhAnh", b =>
                {
                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.HinhAnh", "IdHinhAnhNavigation")
                        .WithMany("ChiTietHinhAnhs")
                        .HasForeignKey("IdHinhAnh")
                        .HasConstraintName("fk_ctha_hinhanh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.MauSac", "MauSacNavigation")
                        .WithMany("ChiTietHinhAnhs")
                        .HasForeignKey("IdMaMau")
                        .HasConstraintName("fk_ctha_mausac")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("ChiTietHinhAnhs")
                        .HasForeignKey("MaSanPham")
                        .HasConstraintName("fk_ctha_sanpham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdHinhAnhNavigation");

                    b.Navigation("MaSanPhamNavigation");

                    b.Navigation("MauSacNavigation");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.ChiTietNhapXuat", b =>
                {
                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.PhieuNhapXuat", "PhieuNhapXuatNavigation")
                        .WithMany("ChiTietNhapXuats")
                        .HasForeignKey("IDPN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.SanPham", "SanPhamNavigation")
                        .WithMany("ChiTietNhapXuats")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuNhapXuatNavigation");

                    b.Navigation("SanPhamNavigation");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.DanhMucDetails", b =>
                {
                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.SanPham", "IdSanPhamNavigation")
                        .WithMany("DanhMucDetails")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.DanhMuc", "IdDanhMucNavigation")
                        .WithMany("DanhMucDetails")
                        .HasForeignKey("danhMucId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdDanhMucNavigation");

                    b.Navigation("IdSanPhamNavigation");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.DiaChi", b =>
                {
                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.KhachHang", "KhachHangNavigation")
                        .WithMany("DiaChis")
                        .HasForeignKey("IDKH");

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.TaiKhoan", "TaiKhoanNavigation")
                        .WithMany("DiaChis")
                        .HasForeignKey("TenTaiKhoan");

                    b.Navigation("KhachHangNavigation");

                    b.Navigation("TaiKhoanNavigation");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.Message", b =>
                {
                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.Message", "MessageNavigation")
                        .WithMany("Messages")
                        .HasForeignKey("ParentMessageID");

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.TaiKhoan", "userNavigation")
                        .WithMany("Messages")
                        .HasForeignKey("creatorID");

                    b.Navigation("MessageNavigation");

                    b.Navigation("userNavigation");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.NCC", b =>
                {
                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.DiaChi", "DiaChiNavigation")
                        .WithMany("NhaCungCaps")
                        .HasForeignKey("IDDiaChi")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("DiaChiNavigation");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.PhieuNhapXuat", b =>
                {
                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.Coupon", "CouponNavigation")
                        .WithMany("PhieuNhapXuats")
                        .HasForeignKey("CouponNavigationMaCoupon");

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.NCC", "NhaCungCapNavigation")
                        .WithMany("PhieuNhapXuats")
                        .HasForeignKey("IDNCC")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.DiaChi", "DiaChiNavigation")
                        .WithMany("PhieuNhapXuats")
                        .HasForeignKey("IdDiaChi")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.KhachHang", "KhachHangNavigation")
                        .WithMany()
                        .HasForeignKey("KhachHangNavigationId");

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.LoaiPhieu", "LoaiPhieuNavigation")
                        .WithMany("PhieuNhapXuats")
                        .HasForeignKey("LoaiPhieu")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.Branchs", "KhoHangNavigation")
                        .WithMany("PhieuNhapXuats")
                        .HasForeignKey("MaChiNhanh")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.TaiKhoan", "TenTaiKhoanNavigation")
                        .WithMany("PhieuNhapXuats")
                        .HasForeignKey("idTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CouponNavigation");

                    b.Navigation("DiaChiNavigation");

                    b.Navigation("KhachHangNavigation");

                    b.Navigation("KhoHangNavigation");

                    b.Navigation("LoaiPhieuNavigation");

                    b.Navigation("NhaCungCapNavigation");

                    b.Navigation("TenTaiKhoanNavigation");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.ReviewStar", b =>
                {
                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.SanPham", "MasanPhamNavigation")
                        .WithMany("ReviewStars")
                        .HasForeignKey("MaSanPham")
                        .HasConstraintName("fk_reviewStar_sanpham")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("MasanPhamNavigation");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.RoomMessage", b =>
                {
                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.SanPham", "SanPhamNavigation")
                        .WithMany("RoomMessages")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.Message", "MessageNavigation")
                        .WithMany("RoomMessages")
                        .HasForeignKey("MessageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.TaiKhoan", "TaiKhoanNavigation")
                        .WithMany("RoomMessages")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MessageNavigation");

                    b.Navigation("SanPhamNavigation");

                    b.Navigation("TaiKhoanNavigation");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.SanPham", b =>
                {
                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.HinhAnh", "HinhAnhNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("IDAnh");

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.Brand", "BrandNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("IDBrand")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.MauSac", "MauSacNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("IDColor");

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.Size", "SizeNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("IDSize")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.Type", "TypeNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("IDType")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.VAT", "VatNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("IDVat")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.BoSuuTap", "IdBstNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdBst")
                        .HasConstraintName("fk_sanpham_BST")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.SanPham", "SanPhamNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("ParentID");

                    b.Navigation("BrandNavigation");

                    b.Navigation("HinhAnhNavigation");

                    b.Navigation("IdBstNavigation");

                    b.Navigation("MauSacNavigation");

                    b.Navigation("SanPhamNavigation");

                    b.Navigation("SizeNavigation");

                    b.Navigation("TypeNavigation");

                    b.Navigation("VatNavigation");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.TaiKhoan", b =>
                {
                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.KhachHang", "SdtKhNavigation")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("idKH")
                        .HasConstraintName("fk_TaiKhoan_KH")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("SdtKhNavigation");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.BoSuuTap", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.Branchs", b =>
                {
                    b.Navigation("KhoHangs");

                    b.Navigation("PhieuNhapXuats");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.Brand", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.Coupon", b =>
                {
                    b.Navigation("ChiTietCoupons");

                    b.Navigation("PhieuNhapXuats");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.DanhMuc", b =>
                {
                    b.Navigation("DanhMucDetails");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.DiaChi", b =>
                {
                    b.Navigation("Branchs");

                    b.Navigation("NhaCungCaps");

                    b.Navigation("PhieuNhapXuats");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.HinhAnh", b =>
                {
                    b.Navigation("ChiTietHinhAnhs");

                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.KhachHang", b =>
                {
                    b.Navigation("DiaChis");

                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.LoaiPhieu", b =>
                {
                    b.Navigation("PhieuNhapXuats");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.MauSac", b =>
                {
                    b.Navigation("ChiTietHinhAnhs");

                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.Message", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("RoomMessages");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.NCC", b =>
                {
                    b.Navigation("PhieuNhapXuats");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.PhieuNhapXuat", b =>
                {
                    b.Navigation("ChiTietNhapXuats");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietCoupons");

                    b.Navigation("ChiTietHinhAnhs");

                    b.Navigation("ChiTietNhapXuats");

                    b.Navigation("DanhMucDetails");

                    b.Navigation("KhoHangs");

                    b.Navigation("ReviewStars");

                    b.Navigation("RoomMessages");

                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.Size", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.TaiKhoan", b =>
                {
                    b.Navigation("DiaChis");

                    b.Navigation("Messages");

                    b.Navigation("PhieuNhapXuats");

                    b.Navigation("RoomMessages");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.Type", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.VAT", b =>
                {
                    b.Navigation("SanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
