// <auto-generated />
using System;
using API_DSCS2_WEBBANGIAY.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API_DSCS2_WEBBANGIAY.Migrations
{
    [DbContext(typeof(ShoesEcommereContext))]
    [Migration("20230512083954_initValues")]
    partial class initValues
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.BoSuuTap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Img")
                        .HasColumnType("text");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Show")
                        .HasColumnType("bit");

                    b.Property<string>("Slug")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("char(30)")
                        .HasColumnName("slug")
                        .IsFixedLength(true);

                    b.Property<string>("TenBoSuuTap")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id");

                    b.ToTable("BoSuuTap");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.Branchs", b =>
                {
                    b.Property<string>("MaChiNhanh")
                        .HasColumnType("char(20)");

                    b.Property<int?>("DiaChiNavigationID")
                        .HasColumnType("int");

                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IDAddress")
                        .HasColumnType("int");

                    b.Property<string>("TenChiNhanh")
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("isDefault")
                        .HasColumnType("bit");

                    b.HasKey("MaChiNhanh");

                    b.HasIndex("DiaChiNavigationID");

                    b.ToTable("Branchs");

                    b.HasData(
                        new
                        {
                            MaChiNhanh = "CN01",
                            ID = 0,
                            TenChiNhanh = "Chi nhánh mặc định",
                            isDefault = false
                        });
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.Brand", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogoLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSanPham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("updatedAT")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.ChiNhanh_SanPham", b =>
                {
                    b.Property<string>("MaChiNhanh")
                        .HasColumnType("char(20)");

                    b.Property<string>("MaSanPham")
                        .HasColumnType("char(10)");

                    b.Property<decimal?>("GiaVon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("SoLuongCoTheban")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongHangDangGiao")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongHangDangVe")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<int?>("TonKho")
                        .HasColumnType("int");

                    b.HasKey("MaChiNhanh", "MaSanPham");

                    b.HasIndex("MaSanPham");

                    b.ToTable("KhoHangs");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.ChiTietBST", b =>
                {
                    b.Property<int>("IDBST")
                        .HasColumnType("int");

                    b.Property<string>("MaSanPham")
                        .HasColumnType("char(10)");

                    b.Property<string>("img")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDBST", "MaSanPham");

                    b.HasIndex("MaSanPham");

                    b.ToTable("ChiTietBSTs");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.ChiTietCoupon", b =>
                {
                    b.Property<string>("MaSanPhamX")
                        .HasColumnType("char(10)");

                    b.Property<string>("MaSanPhamY")
                        .HasColumnType("char(10)");

                    b.Property<string>("MaCoupon")
                        .HasColumnType("char(15)");

                    b.Property<string>("LoaiSanPham")
                        .HasColumnType("char(5)");

                    b.Property<string>("imgX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imgY")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSanPhamX", "MaSanPhamY", "MaCoupon");

                    b.HasIndex("MaCoupon");

                    b.HasIndex("MaSanPhamY");

                    b.ToTable("ChiTietCoupons");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.ChiTietHinhAnh", b =>
                {
                    b.Property<string>("MaSanPham")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .IsFixedLength(true);

                    b.Property<int>("IdHinhAnh")
                        .HasColumnType("int")
                        .HasColumnName("_id_HinhAnh");

                    b.Property<string>("IdMaMau")
                        .HasMaxLength(20)
                        .HasColumnType("char(20)");

                    b.Property<int>("IDSanPham")
                        .HasColumnType("int");

                    b.HasKey("MaSanPham", "IdHinhAnh", "IdMaMau")
                        .HasName("pk_CTHA");

                    b.HasIndex("IdMaMau");

                    b.HasIndex(new[] { "IdHinhAnh" }, "IX_ChiTietHinhAnh__id_HinhAnh");

                    b.HasIndex(new[] { "IdHinhAnh" }, "IX_HinhAnh_SanPham__id_HinhAnh");

                    b.ToTable("ChiTietHinhAnh");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.ChiTietKhuyenMai", b =>
                {
                    b.Property<string>("maSanPham")
                        .HasColumnType("char(10)");

                    b.Property<int>("IDDotKhuyenMai")
                        .HasColumnType("int");

                    b.Property<decimal?>("GiaTri")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("KieuGiaTri")
                        .HasColumnType("int");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("maSanPham", "IDDotKhuyenMai");

                    b.HasIndex("IDDotKhuyenMai");

                    b.ToTable("ChiTietKhuyenMais");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.ChiTietNhapXuat", b =>
                {
                    b.Property<string>("MaSanPham")
                        .HasColumnType("char(10)");

                    b.Property<int>("IDPN")
                        .HasColumnType("int");

                    b.Property<string>("DVT")
                        .HasColumnType("char(10)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenPhieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("createdAT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("deletedAT")
                        .HasColumnType("datetime2");

                    b.Property<string>("img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updatedAT")
                        .HasColumnType("datetime2");

                    b.HasKey("MaSanPham", "IDPN");

                    b.HasIndex("IDPN");

                    b.ToTable("ChiTietNhapXuats");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.Coupon", b =>
                {
                    b.Property<string>("MaCoupon")
                        .HasColumnType("char(15)");

                    b.Property<decimal>("GiaTri")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiaTriDonHangToiThieu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LoaiKhuyenMai")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhomDoiTuong")
                        .HasColumnType("int");

                    b.Property<int>("SoLanDung")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongSPToiThieu")
                        .HasColumnType("int");

                    b.Property<string>("TenCoupon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("trangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaCoupon");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.Coupons_KhachHang", b =>
                {
                    b.Property<string>("MaCoupon")
                        .HasColumnType("char(15)");

                    b.Property<string>("TenTaiKhoan")
                        .HasColumnType("char(50)");

                    b.Property<decimal>("SoLanDaMua")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTienThanhToan")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaCoupon", "TenTaiKhoan");

                    b.HasIndex("TenTaiKhoan");

                    b.ToTable("Coupons_KhachHangs");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.DanhMuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ParentCategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("char(30)")
                        .HasColumnName("slug")
                        .IsFixedLength(true);

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DanhMuc");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.DanhMucDetails", b =>
                {
                    b.Property<int>("danhMucId")
                        .HasColumnType("int");

                    b.Property<string>("MaSanPham")
                        .HasColumnType("char(10)");

                    b.Property<int>("IDSanPham")
                        .HasColumnType("int");

                    b.HasKey("danhMucId", "MaSanPham");

                    b.HasIndex("MaSanPham");

                    b.ToTable("DanhMucDetails");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.DiaChi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressDsc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DistrictID")
                        .HasColumnType("int");

                    b.Property<string>("DistrictName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("char(254)");

                    b.Property<int?>("IDKH")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Phone")
                        .HasColumnType("char(10)");

                    b.Property<int?>("ProvinceID")
                        .HasColumnType("int");

                    b.Property<string>("ProvinceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTaiKhoan")
                        .HasColumnType("char(50)");

                    b.Property<int?>("WardID")
                        .HasColumnType("int");

                    b.Property<string>("WardName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("IDKH");

                    b.HasIndex("TenTaiKhoan");

                    b.ToTable("DiaChis");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.GenKey", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("ID");

                    b.ToTable("Keys");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.HinhAnh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FileName")
                        .HasColumnType("char(255)")
                        .HasColumnName("file_name");

                    b.HasKey("Id");

                    b.ToTable("HinhAnh");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.KhachHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .IsFixedLength(true)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("char(30)")
                        .IsFixedLength(true);

                    b.Property<int?>("GiamGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<bool?>("Gioitinh")
                        .HasColumnType("bit")
                        .HasColumnName("gioitinh");

                    b.Property<DateTime?>("Ngaysinh")
                        .HasColumnType("date")
                        .HasColumnName("ngaysinh");

                    b.Property<string>("TenKhachHang")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal?>("TienThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("money")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("Id")
                        .HasName("pk_KH");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.KhuyenMai", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("GiaTriGiamGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("KieuGiaTri")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("ntext");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenKhuyenMai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("KhuyenMais");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.LoaiPhieu", b =>
                {
                    b.Property<string>("MaPhieu")
                        .HasColumnType("char(10)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenPhieu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhieu");

                    b.ToTable("LoaiPhieu");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.MauSac", b =>
                {
                    b.Property<string>("MaMau")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .HasDefaultValueSql("('')")
                        .IsFixedLength(true);

                    b.Property<string>("TenMau")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("(N'')");

                    b.HasKey("MaMau")
                        .HasName("pk_mausac");

                    b.ToTable("MauSac");

                    b.HasData(
                        new
                        {
                            MaMau = "red"
                        },
                        new
                        {
                            MaMau = "black"
                        },
                        new
                        {
                            MaMau = "white"
                        },
                        new
                        {
                            MaMau = "blue"
                        },
                        new
                        {
                            MaMau = "green"
                        },
                        new
                        {
                            MaMau = "browb"
                        },
                        new
                        {
                            MaMau = "fuchsia"
                        },
                        new
                        {
                            MaMau = "aqua"
                        },
                        new
                        {
                            MaMau = "yellow"
                        },
                        new
                        {
                            MaMau = "maroon"
                        },
                        new
                        {
                            MaMau = "silver"
                        },
                        new
                        {
                            MaMau = "purple"
                        },
                        new
                        {
                            MaMau = "olive"
                        },
                        new
                        {
                            MaMau = "gray"
                        },
                        new
                        {
                            MaMau = "teal"
                        });
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.Message", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentMessageID")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAT")
                        .HasColumnType("datetime2");

                    b.Property<string>("creatorID")
                        .HasColumnType("char(50)");

                    b.HasKey("ID");

                    b.HasIndex("ParentMessageID");

                    b.HasIndex("creatorID");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.NCC", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("char(50)");

                    b.Property<int?>("IDDiaChi")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasColumnType("char(10)");

                    b.HasKey("ID");

                    b.HasIndex("IDDiaChi");

                    b.ToTable("NhaCungCap");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.PhieuNhapXuat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ChietKhau")
                        .HasColumnType("int");

                    b.Property<string>("CouponCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CouponNavigationMaCoupon")
                        .HasColumnType("char(15)");

                    b.Property<bool?>("DaHoanTien")
                        .HasColumnType("bit");

                    b.Property<bool?>("DaNhanHang")
                        .HasColumnType("bit");

                    b.Property<bool?>("DaNhapHang")
                        .HasColumnType("bit");

                    b.Property<bool?>("DaReview")
                        .HasColumnType("bit");

                    b.Property<bool?>("DaThanhToan")
                        .HasColumnType("bit");

                    b.Property<bool?>("DaTraHang")
                        .HasColumnType("bit");

                    b.Property<bool?>("DaVeKho")
                        .HasColumnType("bit");

                    b.Property<bool?>("DaXuatKho")
                        .HasColumnType("bit");

                    b.Property<int?>("DeliveryStatus")
                        .HasColumnType("int");

                    b.Property<int?>("IDNCC")
                        .HasColumnType("int");

                    b.Property<int?>("IdDiaChi")
                        .HasColumnType("int");

                    b.Property<int?>("KhachHangNavigationId")
                        .HasColumnType("int");

                    b.Property<string>("LoaiPhieu")
                        .HasColumnType("char(10)");

                    b.Property<string>("MaChiNhanh")
                        .HasColumnType("char(20)");

                    b.Property<decimal?>("Phiship")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PhuongThucThanhToan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TienDaGiam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TienDaThanhToan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TongSoLuong")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("deletedAT")
                        .HasColumnType("datetime2");

                    b.Property<int?>("idKH")
                        .HasColumnType("int");

                    b.Property<string>("idTaiKhoan")
                        .HasColumnType("char(50)");

                    b.Property<int?>("status")
                        .HasColumnType("int");

                    b.Property<int?>("steps")
                        .HasColumnType("int");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CouponNavigationMaCoupon");

                    b.HasIndex("IDNCC");

                    b.HasIndex("IdDiaChi");

                    b.HasIndex("KhachHangNavigationId");

                    b.HasIndex("LoaiPhieu");

                    b.HasIndex("MaChiNhanh");

                    b.HasIndex("idTaiKhoan");

                    b.ToTable("PhieuNhapXuats");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.ReviewStar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("Avr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasColumnName("avr")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("BaSao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ba_sao")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("BonSao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("bon_sao")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("HaiSao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("hai_sao")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("MotSao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mot_sao")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("NamSao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("nam_sao")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("SanPhamMaSanPham")
                        .HasColumnType("char(10)");

                    b.Property<int?>("total")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SanPhamMaSanPham");

                    b.ToTable("reviewStar");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.Role", b =>
                {
                    b.Property<string>("RoleCode")
                        .HasColumnType("char(15)");

                    b.Property<string>("RoleDsc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleCode");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleCode = "CATMANAGER",
                            RoleDsc = "Thêm, sửa, xóa, danh mục",
                            RoleName = "Quản lý danh mục",
                            Type = ""
                        },
                        new
                        {
                            RoleCode = "MEMANAGER",
                            RoleDsc = "Quản lý tài khoản hội viên",
                            RoleName = "Quản lý thành viên",
                            Type = ""
                        },
                        new
                        {
                            RoleCode = "BSTMNG",
                            RoleName = "Quản lý bộ sưu tập",
                            Type = ""
                        },
                        new
                        {
                            RoleCode = "PNMANAGER",
                            RoleName = "Quản lý phiếu nhập",
                            Type = ""
                        },
                        new
                        {
                            RoleCode = "ORDERMNG",
                            RoleName = "Quản lý đơn hàng",
                            Type = ""
                        },
                        new
                        {
                            RoleCode = "INVENTORYMNG",
                            RoleName = "Quản lý kho hàng",
                            Type = ""
                        },
                        new
                        {
                            RoleCode = "COUPONMNG",
                            RoleName = "Quản lý Coupon",
                            Type = ""
                        },
                        new
                        {
                            RoleCode = "SALEMNG",
                            RoleName = "Quản lý Khuyến mãi",
                            Type = ""
                        });
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.RoleDetails", b =>
                {
                    b.Property<string>("RoleCode")
                        .HasColumnType("char(15)");

                    b.Property<string>("RoleGroup")
                        .HasColumnType("char(20)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("RoleCode", "RoleGroup");

                    b.HasIndex("RoleGroup");

                    b.ToTable("RoleDetails");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.RoleGroup", b =>
                {
                    b.Property<string>("GroupName")
                        .HasColumnType("char(20)");

                    b.Property<string>("GroupDsc")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("GroupName");

                    b.ToTable("RoleGroup");

                    b.HasData(
                        new
                        {
                            GroupName = "ADMIN"
                        },
                        new
                        {
                            GroupName = "MANAGER"
                        },
                        new
                        {
                            GroupName = "USER"
                        });
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.RoomMessage", b =>
                {
                    b.Property<int>("MessageID")
                        .HasColumnType("int");

                    b.Property<string>("MaSanPham")
                        .HasColumnType("char(10)");

                    b.Property<string>("UserID")
                        .HasColumnType("char(50)");

                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IDSanPham")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAT")
                        .HasColumnType("datetime2");

                    b.HasKey("MessageID", "MaSanPham", "UserID");

                    b.HasIndex("MaSanPham");

                    b.HasIndex("UserID");

                    b.ToTable("RoomMessages");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Dsc")
                        .HasColumnType("ntext");

                    b.Property<int>("Giamgia")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayBatDat")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Sale");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.SanPham", b =>
                {
                    b.Property<string>("MaSanPham")
                        .HasColumnType("char(10)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<decimal?>("GiaBanLe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GiaBanSi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GiaNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GiaVon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("GiamGia")
                        .HasColumnType("int");

                    b.Property<int?>("IDAnh")
                        .HasColumnType("int");

                    b.Property<int?>("IDBrand")
                        .HasColumnType("int");

                    b.Property<string>("IDColor")
                        .HasColumnType("char(20)");

                    b.Property<string>("IDSize")
                        .HasColumnType("char(10)");

                    b.Property<int?>("IDType")
                        .HasColumnType("int");

                    b.Property<int?>("IDVat")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Mota")
                        .HasColumnType("ntext");

                    b.Property<string>("MotaChiTiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentID")
                        .HasColumnType("char(10)");

                    b.Property<int?>("ReviewID")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("char(500)")
                        .HasColumnName("slug")
                        .IsFixedLength(true);

                    b.Property<int?>("SoLuongCoTheban")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongDaBan")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("TienDaGiam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int?>("ViewCount")
                        .HasColumnType("int");

                    b.Property<bool?>("isSale")
                        .HasColumnType("bit");

                    b.HasKey("MaSanPham")
                        .HasName("pk_sanpham");

                    b.HasIndex("IDAnh");

                    b.HasIndex("IDBrand");

                    b.HasIndex("IDColor");

                    b.HasIndex("IDSize");

                    b.HasIndex("IDType");

                    b.HasIndex("IDVat");

                    b.HasIndex("ParentID");

                    b.HasIndex("ReviewID")
                        .IsUnique()
                        .HasFilter("[ReviewID] IS NOT NULL");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.Size", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(10)");

                    b.Property<string>("Size1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("size");

                    b.HasKey("Id");

                    b.ToTable("Sizes");

                    b.HasData(
                        new
                        {
                            Id = "25",
                            Size1 = "25"
                        },
                        new
                        {
                            Id = "26",
                            Size1 = "26"
                        },
                        new
                        {
                            Id = "27",
                            Size1 = "27"
                        },
                        new
                        {
                            Id = "28",
                            Size1 = "28"
                        },
                        new
                        {
                            Id = "29",
                            Size1 = "29"
                        },
                        new
                        {
                            Id = "30",
                            Size1 = "30"
                        },
                        new
                        {
                            Id = "31",
                            Size1 = "31"
                        },
                        new
                        {
                            Id = "32",
                            Size1 = "32"
                        },
                        new
                        {
                            Id = "33",
                            Size1 = "33"
                        },
                        new
                        {
                            Id = "34",
                            Size1 = "34"
                        },
                        new
                        {
                            Id = "35",
                            Size1 = "35"
                        },
                        new
                        {
                            Id = "36",
                            Size1 = "36"
                        },
                        new
                        {
                            Id = "37",
                            Size1 = "37"
                        },
                        new
                        {
                            Id = "38",
                            Size1 = "38"
                        },
                        new
                        {
                            Id = "39",
                            Size1 = "39"
                        },
                        new
                        {
                            Id = "40",
                            Size1 = "40"
                        },
                        new
                        {
                            Id = "41",
                            Size1 = "41"
                        },
                        new
                        {
                            Id = "42",
                            Size1 = "42"
                        },
                        new
                        {
                            Id = "43",
                            Size1 = "43"
                        },
                        new
                        {
                            Id = "44",
                            Size1 = "44"
                        },
                        new
                        {
                            Id = "45",
                            Size1 = "45"
                        },
                        new
                        {
                            Id = "46",
                            Size1 = "46"
                        },
                        new
                        {
                            Id = "S",
                            Size1 = "S"
                        },
                        new
                        {
                            Id = "M",
                            Size1 = "M"
                        },
                        new
                        {
                            Id = "L",
                            Size1 = "L"
                        },
                        new
                        {
                            Id = "XL",
                            Size1 = "XL"
                        },
                        new
                        {
                            Id = "2XL",
                            Size1 = "2XL"
                        },
                        new
                        {
                            Id = "3XL",
                            Size1 = "3XL"
                        },
                        new
                        {
                            Id = "4XL",
                            Size1 = "4XL"
                        });
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.StarReviewDetail", b =>
                {
                    b.Property<int>("StarReviewID")
                        .HasColumnType("int");

                    b.Property<int>("IDDonHang")
                        .HasColumnType("int");

                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSanPham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasanPhamNavigationMaSanPham")
                        .HasColumnType("char(10)");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.HasKey("StarReviewID", "IDDonHang", "ID");

                    b.HasIndex("IDDonHang");

                    b.HasIndex("MasanPhamNavigationMaSanPham");

                    b.ToTable("StarReviewDetails");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.TaiKhoan", b =>
                {
                    b.Property<string>("TenTaiKhoan")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("char(50)")
                        .IsFixedLength(true);

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("char(30)")
                        .IsFixedLength(true);

                    b.Property<bool?>("Gioitinh")
                        .HasColumnType("bit");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .IsFixedLength(true);

                    b.Property<int?>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("RoleGroup")
                        .HasColumnType("char(20)");

                    b.Property<int?>("SoLanMuaHang")
                        .HasColumnType("int");

                    b.Property<string>("TenHienThi")
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("TienThanhToan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("addressDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("-1");

                    b.Property<int?>("idKH")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .IsFixedLength(true);

                    b.Property<bool?>("isActive")
                        .HasColumnType("bit");

                    b.Property<bool>("isBlocked")
                        .HasColumnType("bit");

                    b.HasKey("TenTaiKhoan");

                    b.HasIndex("RoleGroup");

                    b.HasIndex("idKH");

                    b.ToTable("TaiKhoan");

                    b.HasData(
                        new
                        {
                            TenTaiKhoan = "admin",
                            Avatar = "",
                            MatKhau = "admin",
                            RoleGroup = "ADMIN",
                            SoLanMuaHang = 0,
                            TenHienThi = "",
                            TienThanhToan = 0m,
                            isActive = false,
                            isBlocked = false
                        });
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.Type", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MaSanPham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Slug")
                        .HasColumnType("char(50)");

                    b.Property<DateTime>("createdAT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("updatedAT")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.VAT", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MaSanPham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("giaTriThueDauRa")
                        .HasColumnType("int");

                    b.Property<int>("giaTriThueDauVao")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Vats");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.Branchs", b =>
                {
                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.DiaChi", "DiaChiNavigation")
                        .WithMany("Branchs")
                        .HasForeignKey("DiaChiNavigationID");

                    b.Navigation("DiaChiNavigation");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.ChiNhanh_SanPham", b =>
                {
                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.Branchs", "BranchNavigation")
                        .WithMany("KhoHangs")
                        .HasForeignKey("MaChiNhanh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.SanPham", "SanPhamNavigation")
                        .WithMany("KhoHangs")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BranchNavigation");

                    b.Navigation("SanPhamNavigation");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.ChiTietBST", b =>
                {
                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.BoSuuTap", "BSTNavigation")
                        .WithMany("ChiTietBSTs")
                        .HasForeignKey("IDBST")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.SanPham", "SanPhamNavigation")
                        .WithMany("ChiTietBSTs")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BSTNavigation");

                    b.Navigation("SanPhamNavigation");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.ChiTietCoupon", b =>
                {
                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.Coupon", "CouponNavigation")
                        .WithMany("ChiTietCoupons")
                        .HasForeignKey("MaCoupon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.SanPham", "SanPhamXNavigation")
                        .WithMany("ChiTietCouponsX")
                        .HasForeignKey("MaSanPhamX")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.SanPham", "SanPhamYNavigation")
                        .WithMany("ChiTietCouponsY")
                        .HasForeignKey("MaSanPhamY")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CouponNavigation");

                    b.Navigation("SanPhamXNavigation");

                    b.Navigation("SanPhamYNavigation");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.ChiTietHinhAnh", b =>
                {
                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.HinhAnh", "IdHinhAnhNavigation")
                        .WithMany("ChiTietHinhAnhs")
                        .HasForeignKey("IdHinhAnh")
                        .HasConstraintName("fk_ctha_hinhanh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.MauSac", "MauSacNavigation")
                        .WithMany("ChiTietHinhAnhs")
                        .HasForeignKey("IdMaMau")
                        .HasConstraintName("fk_ctha_mausac")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("ChiTietHinhAnhs")
                        .HasForeignKey("MaSanPham")
                        .HasConstraintName("fk_ctha_sanpham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdHinhAnhNavigation");

                    b.Navigation("MaSanPhamNavigation");

                    b.Navigation("MauSacNavigation");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.ChiTietKhuyenMai", b =>
                {
                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.KhuyenMai", "KhuyenMaiNavigation")
                        .WithMany("ChiTietKhuyenMais")
                        .HasForeignKey("IDDotKhuyenMai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.SanPham", "SanPhamNavigation")
                        .WithMany("ChiTietKhuyenMais")
                        .HasForeignKey("maSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhuyenMaiNavigation");

                    b.Navigation("SanPhamNavigation");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.ChiTietNhapXuat", b =>
                {
                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.PhieuNhapXuat", "PhieuNhapXuatNavigation")
                        .WithMany("ChiTietNhapXuats")
                        .HasForeignKey("IDPN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.SanPham", "SanPhamNavigation")
                        .WithMany("ChiTietNhapXuats")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuNhapXuatNavigation");

                    b.Navigation("SanPhamNavigation");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.Coupons_KhachHang", b =>
                {
                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.Coupon", "CouponNavigation")
                        .WithMany("CouponsKhachHang")
                        .HasForeignKey("MaCoupon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.TaiKhoan", "TaiKhoanNavigation")
                        .WithMany("CouponsKhachHangs")
                        .HasForeignKey("TenTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CouponNavigation");

                    b.Navigation("TaiKhoanNavigation");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.DanhMucDetails", b =>
                {
                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.SanPham", "IdSanPhamNavigation")
                        .WithMany("DanhMucDetails")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.DanhMuc", "IdDanhMucNavigation")
                        .WithMany("DanhMucDetails")
                        .HasForeignKey("danhMucId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdDanhMucNavigation");

                    b.Navigation("IdSanPhamNavigation");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.DiaChi", b =>
                {
                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.KhachHang", "KhachHangNavigation")
                        .WithMany("DiaChis")
                        .HasForeignKey("IDKH");

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.TaiKhoan", "TaiKhoanNavigation")
                        .WithMany("DiaChis")
                        .HasForeignKey("TenTaiKhoan");

                    b.Navigation("KhachHangNavigation");

                    b.Navigation("TaiKhoanNavigation");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.Message", b =>
                {
                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.Message", "MessageNavigation")
                        .WithMany("Messages")
                        .HasForeignKey("ParentMessageID");

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.TaiKhoan", "userNavigation")
                        .WithMany("Messages")
                        .HasForeignKey("creatorID");

                    b.Navigation("MessageNavigation");

                    b.Navigation("userNavigation");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.NCC", b =>
                {
                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.DiaChi", "DiaChiNavigation")
                        .WithMany("NhaCungCaps")
                        .HasForeignKey("IDDiaChi")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("DiaChiNavigation");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.PhieuNhapXuat", b =>
                {
                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.Coupon", "CouponNavigation")
                        .WithMany("PhieuNhapXuats")
                        .HasForeignKey("CouponNavigationMaCoupon");

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.NCC", "NhaCungCapNavigation")
                        .WithMany("PhieuNhapXuats")
                        .HasForeignKey("IDNCC")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.DiaChi", "DiaChiNavigation")
                        .WithMany("PhieuNhapXuats")
                        .HasForeignKey("IdDiaChi")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.KhachHang", "KhachHangNavigation")
                        .WithMany()
                        .HasForeignKey("KhachHangNavigationId");

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.LoaiPhieu", "LoaiPhieuNavigation")
                        .WithMany("PhieuNhapXuats")
                        .HasForeignKey("LoaiPhieu")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.Branchs", "KhoHangNavigation")
                        .WithMany("PhieuNhapXuats")
                        .HasForeignKey("MaChiNhanh")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.TaiKhoan", "TenTaiKhoanNavigation")
                        .WithMany("PhieuNhapXuats")
                        .HasForeignKey("idTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CouponNavigation");

                    b.Navigation("DiaChiNavigation");

                    b.Navigation("KhachHangNavigation");

                    b.Navigation("KhoHangNavigation");

                    b.Navigation("LoaiPhieuNavigation");

                    b.Navigation("NhaCungCapNavigation");

                    b.Navigation("TenTaiKhoanNavigation");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.ReviewStar", b =>
                {
                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.SanPham", null)
                        .WithMany("ReviewStars")
                        .HasForeignKey("SanPhamMaSanPham");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.RoleDetails", b =>
                {
                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.Role", "IdRoleNavigation")
                        .WithMany("RoleDetails")
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.RoleGroup", "RoleGroupNavigation")
                        .WithMany("RoleDetails")
                        .HasForeignKey("RoleGroup")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdRoleNavigation");

                    b.Navigation("RoleGroupNavigation");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.RoomMessage", b =>
                {
                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.SanPham", "SanPhamNavigation")
                        .WithMany("RoomMessages")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.Message", "MessageNavigation")
                        .WithMany("RoomMessages")
                        .HasForeignKey("MessageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.TaiKhoan", "TaiKhoanNavigation")
                        .WithMany("RoomMessages")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MessageNavigation");

                    b.Navigation("SanPhamNavigation");

                    b.Navigation("TaiKhoanNavigation");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.SanPham", b =>
                {
                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.HinhAnh", "HinhAnhNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("IDAnh");

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.Brand", "BrandNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("IDBrand")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.MauSac", "MauSacNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("IDColor");

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.Size", "SizeNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("IDSize")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.Type", "TypeNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("IDType")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.VAT", "VatNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("IDVat")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.SanPham", "SanPhamNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("ParentID");

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.ReviewStar", "StarReviewNavigation")
                        .WithOne("SanPhamNavigation")
                        .HasForeignKey("API_DSCS2_WEBBANGIAY.Models.SanPham", "ReviewID");

                    b.Navigation("BrandNavigation");

                    b.Navigation("HinhAnhNavigation");

                    b.Navigation("MauSacNavigation");

                    b.Navigation("SanPhamNavigation");

                    b.Navigation("SizeNavigation");

                    b.Navigation("StarReviewNavigation");

                    b.Navigation("TypeNavigation");

                    b.Navigation("VatNavigation");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.StarReviewDetail", b =>
                {
                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.PhieuNhapXuat", "HoaDonNavigation")
                        .WithMany("StarReviewDetails")
                        .HasForeignKey("IDDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.SanPham", "MasanPhamNavigation")
                        .WithMany()
                        .HasForeignKey("MasanPhamNavigationMaSanPham");

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.ReviewStar", "ReviewStarNavigation")
                        .WithMany("StarReviewDetails")
                        .HasForeignKey("StarReviewID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDonNavigation");

                    b.Navigation("MasanPhamNavigation");

                    b.Navigation("ReviewStarNavigation");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.TaiKhoan", b =>
                {
                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.RoleGroup", "RoleGroupNavigation")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("RoleGroup")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("API_DSCS2_WEBBANGIAY.Models.KhachHang", "SdtKhNavigation")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("idKH")
                        .HasConstraintName("fk_TaiKhoan_KH")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("RoleGroupNavigation");

                    b.Navigation("SdtKhNavigation");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.BoSuuTap", b =>
                {
                    b.Navigation("ChiTietBSTs");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.Branchs", b =>
                {
                    b.Navigation("KhoHangs");

                    b.Navigation("PhieuNhapXuats");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.Brand", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.Coupon", b =>
                {
                    b.Navigation("ChiTietCoupons");

                    b.Navigation("CouponsKhachHang");

                    b.Navigation("PhieuNhapXuats");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.DanhMuc", b =>
                {
                    b.Navigation("DanhMucDetails");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.DiaChi", b =>
                {
                    b.Navigation("Branchs");

                    b.Navigation("NhaCungCaps");

                    b.Navigation("PhieuNhapXuats");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.HinhAnh", b =>
                {
                    b.Navigation("ChiTietHinhAnhs");

                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.KhachHang", b =>
                {
                    b.Navigation("DiaChis");

                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.KhuyenMai", b =>
                {
                    b.Navigation("ChiTietKhuyenMais");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.LoaiPhieu", b =>
                {
                    b.Navigation("PhieuNhapXuats");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.MauSac", b =>
                {
                    b.Navigation("ChiTietHinhAnhs");

                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.Message", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("RoomMessages");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.NCC", b =>
                {
                    b.Navigation("PhieuNhapXuats");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.PhieuNhapXuat", b =>
                {
                    b.Navigation("ChiTietNhapXuats");

                    b.Navigation("StarReviewDetails");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.ReviewStar", b =>
                {
                    b.Navigation("SanPhamNavigation");

                    b.Navigation("StarReviewDetails");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.Role", b =>
                {
                    b.Navigation("RoleDetails");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.RoleGroup", b =>
                {
                    b.Navigation("RoleDetails");

                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietBSTs");

                    b.Navigation("ChiTietCouponsX");

                    b.Navigation("ChiTietCouponsY");

                    b.Navigation("ChiTietHinhAnhs");

                    b.Navigation("ChiTietKhuyenMais");

                    b.Navigation("ChiTietNhapXuats");

                    b.Navigation("DanhMucDetails");

                    b.Navigation("KhoHangs");

                    b.Navigation("ReviewStars");

                    b.Navigation("RoomMessages");

                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.Size", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.TaiKhoan", b =>
                {
                    b.Navigation("CouponsKhachHangs");

                    b.Navigation("DiaChis");

                    b.Navigation("Messages");

                    b.Navigation("PhieuNhapXuats");

                    b.Navigation("RoomMessages");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.Type", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("API_DSCS2_WEBBANGIAY.Models.VAT", b =>
                {
                    b.Navigation("SanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
